---
Date: 2022-07-31 20:51:00
LastEditors: Hwrn hwrn.aou@sjtu.edu.cn
LastEditTime: 2024-03-05 13:20:49
FilePath: /2021_09-MT10kSW/results/Rmd/check_ko_tpm_clade_N.Rmd
Description:
output:
  html_document:
    df_print: paged
    theme: cerulean
    highlight: haddock
    toc: yes
    toc_depth: 3
    toc_float:
      collapsed: no
      smooth_scroll: yes
    code_fold: hide
title: tree of genes related to N cycling in AOA
---

## Data Import and prepare

```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = "~/Work/2021_09-MT10kSW/")
options(width = 120)
```
```{r config, message=FALSE, warning=FALSE}
source("workflow/utils/RLib.local/R/init.r", chdir = TRUE)
```

```{r load_data}
stdb <- load__Stdb()
wtdb <- load__Wtdb()
genome_taxonomy <- load__genome_taxonomy(load__Stdb(), load__Wtdb())

genome_rltabd <- stringr::str_glue("Wtdb.relative_abundance.tsv") %>%
  file_path$file_path$results(.) %>%
  as.character() %>%
  get_relative_abundance(genome_taxonomy)

key_genes <- load__key_genes()
key_genes_N <- key_genes %>% # nolint: object_name_linter.
  filter(get("Pathway") == "N") %>%
  mutate(Pathway = get("Arrow") %>% factor(levels = unique(.)))

key_genes_aoa <- data.frame(
  KO = c(
    as.character(key_genes_N$KO),
    "K03182", "K03741", "K03892", "K00657", "K07086"
  ) %>% factor(., levels = .),
  Label = c(
    as.character(key_genes_N$Label),
    "ubiE", "arsC2", "arsR", "sepG", "K07086"
  ) %>% factor(., levels = .)
)

gene_ko_tpm_N <- load__gene_ko_tpm() %>% # nolint: object_name_linter.
  .[.$KO %in% key_genes_aoa$KO, ]
```

```{r genome_group}
genome_ext <- genome_rltabd %>%
  with(
    data.frame(
      Genome = get("Genome"),
      Class = taxon.split(get("Taxonomy"), 1, 3),
      Taxonomy = taxon.split(get("Taxonomy"), 1, 7),
      Layer = get("Layer"),
      Group = get("Group"),
      Exist = TRUE
    )
  )
key_gene_genome_layer <- gene_ko_tpm_N %>%
  mutate(Genome = gsub(".fa$", "", get("Genome"))) %>%
  merge(genome_taxonomy[c("Cluster", "Genome")]) %>%
  mutate(Genome = NULL) %>%
  merge(
    genome_taxonomy[c("Cluster", "Genome", "Rep")] %>% .[.$Rep, ]
  ) %>%
  group_by(KO = get("KO"), Layer = get("Layer"), Genome = get("Genome")) %>%
  summarise(GPM = sum(get("TPM"))) %>%
  merge(unique(genome_ext[c("Layer", "Group")])) %>%
  merge(genome_ext[c("Genome", "Layer", "Exist")], all.x = TRUE) %>%
  mutate(GPM.adj = get("GPM") * (1 - 2 * is.na(get("Exist"))))
```

```{r tree function}
#' @title load a phylogenetic tree and fold at outgroup
#'
#' @param tree_file <str> file to out_group
#' @param out_group <c[str]> an array of outgroup labels
#'
#' @return a tree that reroot at outgroup, and sort as iTol does.
load__tree <- function(tree_file, out_group) {
  tre <- ape::read.tree(tree_file)

  genome_a <- tre$tip.label %>% .[. %in% out_group] # nolint: object_usage_linter, line_length_linter.
  genome_b <- tre$tip.label %>% .[!. %in% genome_a] # nolint: object_usage_linter, line_length_linter.
  roots <- c(A = ape::getMRCA(tre, genome_a), B = ape::getMRCA(tre, genome_b))

  if (!ape::is.monophyletic(tre, genome_a)) {
    warning("outgroup is not monophyletic, updating")
    genome_a <- roots %>% # nolint: object_usage_linter.
      lapply(
        . %>%
          ape::extract.clade(tre, node = .) %>%
          .$tip.label
      ) %>%
      {
        .[[which.min(sapply(., length))]]
      }
    genome_b <- tre$tip.label %>% .[!. %in% genome_a] # nolint: object_usage_linter, line_length_linter.
    roots <- c(A = ape::getMRCA(tre, genome_a), B = ape::getMRCA(tre, genome_b))
  }

  mid_root_len <- c(
    ape::root.phylo(tre, genome_a) %>% # nolint: object_usage_linter, line_length_linter.
      {
        .$edge.length[]
        apply(
          .$edge, 2,
          . %>% # nolint: object_usage_linter
            {
              . %in% roots
            }
        ) %>%
          apply(1, all)
      },
    ape::root.phylo(tre, genome_b) %>%
      {
        .$edge.length[]
        apply(
          .$edge, 2,
          . %>% # nolint: object_usage_linter
            {
              . %in% roots
            }
        ) %>%
          apply(1, all)
      }
  )[1]

  tre_reroot <- ape::root.phylo(
    ape::unroot(tre), genome_a,
    resolve.root = TRUE
  ) %>% # nolint: object_usage_linter
    {
      ape::bind.tree(
        ape::drop.tip(., genome_a) %>% # nolint: object_usage_linter
          {
            .$root.edge <- mid_root_len
            .
          },
        ape::keep.tip(., genome_a) %>%
          {
            .$root.edge <- mid_root_len
            .
          },
        position = mid_root_len
      )
    }

  TreeTools::SortTree(tre_reroot)
}

load_gene_tree <- function(tree_file) {
  tree_taxons <- tree_file %>% # nolint: object_usage_linter
    ape::read.tree() %>%
    .$tip.label %>% # nolint: object_usage_linter
    {
      genes <- . # nolint: object_usage_linter,
      file_path$file_path$results("gene_map.csv") %>% # nolint: object_usage_linter
        as.character() %>%
        read.csv() %>%
        `colnames<-`(
          colnames(.) %>% str_to_title() # nolint: object_usage_linter
        ) %>%
        .[c("Genome", "Gene")] %>%
        filter(get("Gene") %in% genes)
    } %>%
    mutate(Genome = gsub(".fa$", "", get("Genome"))) %>% # nolint: object_usage_linter
    left_join(genome_taxonomy) %>% # nolint: object_usage_linter
    mutate(
      tip_label = paste0(
        `names<-`(get("Taxonomy"), get("Gene")) %>%
          taxon.split(3, 6) %>% # nolint: object_usage_linter
          as.character(),
        "\n  ",
        `names<-`(get("Genome"), get("Gene")),
        ", ",
        get("Gene")
      )
    )
  gene_tree <- tree_taxons %>% # nolint: object_usage_linter
    with(get("Gene")[taxon.split(get("Taxonomy"), 1, 1) == "Archaea"]) %>% # nolint: object_usage_linter, line_length_linter.
    load__tree(tree_file, .) # nolint: object_usage_linter
  list(file = tree_file, taxon = tree_taxons, tree = gene_tree)
}

plot_gene_tree <- function(
    gene_tree, tree_x_lim = 10, phydata_offset = 6,
    title = "",
    genome_rltabd = get("genome_rltabd", envir = parent.frame()),
    sample_meta_col = get("sample_meta_col", envir = parent.frame())) {
  m <- genome_rltabd %>% # nolint: object_usage_linter
    pivot_wider( # nolint: object_usage_linter,
      id_cols = "Cluster", names_from = "Group", values_from = "Group",
      values_fn = unique, values_fill = ""
    ) %>%
    inner_join( # nolint: object_usage_linter,
      gene_tree$taxon[c("tip_label", "Cluster")],
      by = "Cluster"
    ) %>%
    dplyr::select(!c("Cluster")) %>%
    column_to_rownames("tip_label") %>% # nolint: object_usage_linter,
    apply(2, . %>% factor(c(names(sample_meta_col), ""))) # nolint: object_usage_linter,
  gene_tree$tree$tip.label <- with(
    gene_tree$taxon,
    `names<-`(get("tip_label"), get("Gene"))[gene_tree$tree$tip.label]
  )

  ape::plotBreakLongEdges(
    gene_tree$tree, 2,
    x.lim = tree_x_lim, align.tip = TRUE
  )
  ape::axisPhylo()
  ape::phydataplot(
    m,
    phy = gene_tree$tree,
    style = "mosaic",
    offset = phydata_offset,
    funcol = function(x) sample_meta_col
  )
  graphics::title(title)
}
```

## Ammonia Oxidation (Nitrification)
### amoABC | Ammonia -> Hydroxylamine
```{r fig.height=15, fig.width=3.5}
p1 <- genome_rltabd %>%
  filter(taxon.split(get("Taxonomy"), 3) == "Nitrososphaeria") %>%
  mutate(Genus = as.character(taxon.split(get("Taxonomy"), 6))) %>%
  ggplot() +
  geom_boxplot(
    aes_string(x = "Group", y = "Relative_abundance", fill = "Group")
  ) +
  scale_y_log10(
    labels = ~ format(.x, scientific = TRUE) %>%
      str_replace("^0e\\+0", "0e+0") %>%
      str_replace("e\\+0", "%*%10^") %>%
      parse(text = .)
  ) +
  facet_grid(formula("Cluster + Genus + Genome ~ .")) +
  scale_fill_manual(values = sample_meta_col)
```

```{r fig.height=15, fig.width=14}
key_gene_genome_layer %>%
  filter(
    get("Genome") %in%
      filter(
        genome_taxonomy,
        taxon.split(get("Taxonomy"), 1, 3) ==
          "Archaea;Thermoproteota;Nitrososphaeria"
      )$Genome
  ) %>%
  left_join(key_genes_N) %>%
  left_join(genome_taxonomy[c("Genome", "Cluster", "Taxonomy")]) %>%
  mutate(Genus = as.character(taxon.split(get("Taxonomy"), 6))) %>%
  ggplot() +
  geom_boxplot(
    aes_string(x = "Group", y = "GPM", fill = "Group"),
    data = . %>% filter(!is.na(get("Exist")))
  ) +
  geom_boxplot(
    aes_string(x = "Group", y = "GPM", color = "Exist"),
    data = . %>%
      group_by(
        Genome = get("Genome"),
        KO = get("KO"),
        Group = get("Group")
      ) %>%
      mutate(Exist = sum(!is.na(get("Exist"))) > 0),
    fill = NA,
    alpha = 0.3
  ) +
  scale_y_log10(
    labels = ~ format(.x, scientific = TRUE) %>%
      str_replace("^0e\\+0", "0e+0") %>%
      str_replace("e\\+0", "%*%10^") %>%
      parse(text = .)
  ) +
  facet_grid(formula("Cluster ~ KO + Label")) +
  scale_fill_manual(values = sample_meta_col) +
  p1 +
  plot_layout(
    design = paste(c(rep("A", 12), "B"), collapse = ""), guides = "collect"
  )
```

```{r fig.height=15, fig.width=16}
genome_taxonomy[c("Genome", "Cluster", "Taxonomy")] %>%
  filter(taxon.split(get("Taxonomy"), 3) == "Nitrososphaeria") %>%
  inner_join(key_gene_genome_layer, .) %>%
  left_join(key_genes_aoa) %>%
  mutate(
    Genus = as.character(taxon.split(get("Taxonomy"), 6)),
    Label = factor(get("Label"), levels(key_genes_aoa$Label))
  ) %>%
  ggplot() +
  geom_boxplot(
    aes_string(x = "Group", y = "GPM", fill = "Group"),
    data = . %>% filter(!is.na(get("Exist")))
  ) +
  scale_y_log10(
    labels = ~ format(.x, scientific = TRUE) %>%
      str_replace("^0e\\+0", "0e+0") %>%
      str_replace("e\\+0", "%*%10^") %>%
      parse(text = .)
  ) +
  facet_grid(formula("Cluster ~ Label + KO")) +
  scale_fill_manual(values = sample_meta_col) +
  p1 +
  plot_layout(
    design = paste(c(rep("A", 14), "B"), collapse = ""), guides = "collect"
  ) &
  theme_bw() +
    theme(
      axis.text.x = element_blank(),
      axis.ticks.x = element_blank()
    )
```

```{r amoA all, fig.height=15, fig.width=16}
gene_tree_amoA <- # nolint: object_name_linter,
  "data/AOA_N_genes/amoA_all.afa.trimal.contree" %>%
  load_gene_tree()
plot_gene_tree(gene_tree_amoA, title = "All amoA genes")
```

```{r amoA Rep, fig.height=7, fig.width=16}
gene_tree_amoA %>%
  {
    .$tree <- .$taxon %>%
      with(get("Gene")[taxon.split(get("Taxonomy"), 1, 1) == "Archaea"]) %>%
      load__tree("data/AOA_N_genes/amoA.afa.trimal.contree", .)
    .
  } %>%
  plot_gene_tree(
    tree_x_lim = 10, phydata_offset = 6, title = "Rep amoA genes"
  )
```

```{r amoB all, fig.height=15, fig.width=16}
gene_tree_amoB <- # nolint: object_name_linter,
  "data/AOA_N_genes/amoB_all.afa.trimal.contree" %>%
  load_gene_tree()
plot_gene_tree(gene_tree_amoB, title = "All amoB genes")
```

```{r amoB Rep, fig.height=7, fig.width=16}
"data/AOA_N_genes/amoB.afa.trimal.contree" %>%
  load_gene_tree() %>%
  plot_gene_tree(title = "Rep amoB genes")
```

```{r gdhA, fig.height=50, fig.width=16}
gene_tree_gdhA_rep <- # nolint: object_name_linter,
  "data/AOA_N_genes/gdhA.afa.trimal.contree" %>%
  load_gene_tree()
gene_tree_gdhA_rep %>%
  {
    .$taxon <- mutate(
      .$taxon,
      tip_label = gsub("\n  ", " ", get("tip_label"))
    )
    .
  } %>%
  plot_gene_tree(title = "Rep gdhA genes")
```

```{r gdhA-Archaea, fig.height=10, fig.width=16}
gene_tree_gdhA_rep %>%
  {
    .$tree <- ape::keep.tip(
      .$tree,
      tip = with(
        .$taxon,
        get("Gene")[taxon.split(get("Taxonomy"), 1) == "Archaea"]
      )
    )
    .
  } %>%
  plot_gene_tree(title = "Rep gdhA genes of Archaea")
```

```{r nirK-Archaea, fig.height=15, fig.width=16}
gene_tree_nirK_rep <- # nolint: object_name_linter,
  "data/AOA_N_genes/nirK_ge90.afa.trimal.contree" %>%
  load_gene_tree()
gene_tree_nirK_rep %>%
  {
    .$tree <- ape::keep.tip(
      .$tree,
      tip = with(
        .$taxon,
        get("Gene")[taxon.split(get("Taxonomy"), 1) == "Archaea"]
      )
    )
    .
  } %>%
  plot_gene_tree(title = "Rep nirK genes of Archaea")
```

```{r ureC, fig.height=40, fig.width=16}
gene_tree_ureC_rep <- # nolint: object_name_linter,
  "data/AOA_N_genes/ureC.afa.trimal.contree" %>%
  load_gene_tree()
gene_tree_ureC_rep %>%
  {
    .$taxon <- mutate(
      .$taxon,
      tip_label = gsub("\n  ", " ", get("tip_label"))
    )
    .
  } %>%
  plot_gene_tree(title = "Rep ureC genes", tree_x_lim = 13, phydata_offset = 10)
```

```{r amoA-amoB, fig.height=15, fig.width=30}
cop <- list(amoA = gene_tree_amoA, amoB = gene_tree_amoB) %>%
  lapply(
    . %>%
      {
        tree <- .$tree
        tree$tip.label <- .$taxon %>%
          mutate(
            tip_label1 = paste0(
              `names<-`(get("Taxonomy"), get("Gene")) %>%
                taxon.split(3, 6) %>%
                as.character(),
              "\n  ",
              `names<-`(get("Genome"), get("Gene"))
            )
          ) %>%
          with(`names<-`(get("tip_label1"), get("Gene"))[tree$tip.label])
        tree
      }
  ) %>%
  with(
    phytools::cophylo(
      get("amoA"), get("amoB"),
      assoc = unique(get("amoA")$tip.label, get("amoB")$tip.label) %>%
        cbind(amoA = ., amoB = .),
      rotate = TRUE
    )
  )
cop %>%
  {
    plot(., link.type = "curved")
    text(-0.51, 0.5, "amoA", srt = 90)
    text(0.51, 0.5, "amoB", srt = -90)
  }
```

```{r load genome taxonomy tree, fig.width=12, fig.height=12}
genome_tree <- "04_bin/04_tree/all_mid_20.afa.trimal.contree" %>%
  load__tree(
    with(
      wtdb,
      get("Genome")[taxon.split(get("Taxonomy"), 1) == "Archaea"]
    )
  ) %>%
  {
    ape::plotBreakLongEdges(
      ., 2,
      type = "fan", open.angle = 45, rotate.tree = 135
    )
    ape::axisPhylo()

    .$tip.label <- with(
      wtdb, `names<-`(get("Cluster"), get("Genome"))[.$tip.label]
    )
    .
  }
```

```{r compare genome, fig.height=7, fig.width=8}
genome_tree %>%
  ape::keep.tip(
    .,
    intersect(
      with(
        genome_taxonomy,
        get("Cluster")[taxon.split(get("Taxonomy"), 1) == "Archaea"]
      ),
      .$tip.label
    )
  ) %>%
  {
    m <- genome_rltabd %>%
      pivot_wider(
        id_cols = "Cluster", names_from = "Group", values_from = "Group",
        values_fn = unique, values_fill = ""
      ) %>%
      column_to_rownames("Cluster") %>%
      apply(2, . %>% factor(c(names(sample_meta_col), "")))

    plot(., x.lim = 3, align.tip = TRUE)
    ape::axisPhylo()
    ape::phydataplot(
      m,
      phy = .,
      style = "mosaic",
      offset = 1,
      funcol = function(x) sample_meta_col
    )
    graphics::title("Archaea Gemomes")
  }
```

```{r compare genome and amoAB, fig.height=15, fig.width=27}
compare_tree_gene_genome <- function(
    gene_tree, genome_tree, gene_name = "") {
  gene_tree1 <- gene_tree %>% # nolint: object_usage_linter.
    {
      .$tree$tip.label <- with(
        .$taxon,
        `names<-`(get("tip_label"), get("Gene"))[.$tree$tip.label]
      )
      .$tree
    }
  genome_tree %>% # nolint: object_usage_linter.
    ape::keep.tip(., intersect(gene_tree$taxon$Cluster, .$tip.label)) %>%
    phytools::cophylo(
      gene_tree1,
      assoc = gene_tree$taxon[c("Cluster", "tip_label")],
      rotate = TRUE
    ) %>%
    plot(link.type = "curved")
  text(-0.51, 0.5, "conserved genes", srt = 90)
  text(0.51, 0.5, gene_name, srt = -90)
}
compare_tree_gene_genome(gene_tree_amoA, genome_tree, "amoA")
compare_tree_gene_genome(gene_tree_amoB, genome_tree, "amoB")
```

```{r compare genome and gdhA-Archaea, fig.height=10, fig.width=20}
gene_tree_gdhA_rep %>%
  {
    .$taxon <- filter(.$taxon, taxon.split(get("Taxonomy"), 1) == "Archaea")
    .$tree <- ape::keep.tip(.$tree, tip = .$taxon[, "Gene"])
    .
  } %>%
  compare_tree_gene_genome(., genome_tree, "Rep gdhA genes of Archaea")
```

```{r compare genome and nirK-Archaea, fig.height=18, fig.width=20}
gene_tree_nirK_rep %>%
  {
    .$taxon <- filter(.$taxon, taxon.split(get("Taxonomy"), 1) == "Archaea")
    .$tree <- ape::keep.tip(.$tree, tip = .$taxon[, "Gene"])
    .
  } %>%
  compare_tree_gene_genome(., genome_tree, "Rep nirK genes of Archaea")
```

```{r compare genome and ureC-Archaea, fig.height=6, fig.width=20}
gene_tree_ureC_rep %>%
  {
    .$taxon <- filter(.$taxon, taxon.split(get("Taxonomy"), 1) == "Archaea")
    .$tree <- ape::keep.tip(.$tree, tip = .$taxon[, "Gene"])
    .
  } %>%
  compare_tree_gene_genome(., genome_tree, "Rep ureC genes of Archaea")
```

```{r fig.height=8, fig.width=4}
key_gene_genome_layer %>%
  filter(
    get("Genome") %in%
      filter(
        genome_taxonomy,
        taxon.split(get("Taxonomy"), 1, 3) ==
          "Archaea;Thermoproteota;Nitrososphaeria"
      )$Genome
  ) %>%
  filter(!is.na(get("Exist"))) %>%
  left_join(key_genes_N) %>%
  left_join(genome_taxonomy[c("Genome", "Cluster", "Taxonomy")]) %>%
  filter(get("Label") %in% c("amoA", "gdhA")) %>%
  group_by(
    Cluster = get("Cluster"),
    Genus = as.character(taxon.split(get("Taxonomy"), 6)),
    Genome = get("Genome"),
    Sample = paste0(get("Group"), "_", get("Layer")),
    Group = get("Group")
  ) %>%
  summarise(
    gdhA_per_amoA = c(get("GPM")[which(get("Label") == "gdhA")], 0)[1] /
      c(get("GPM")[which(get("Label") == "amoA")], -1)[1]
  ) %>%
  filter(get("gdhA_per_amoA") > 0) %>%
  print() %>%
  ggplot() +
  geom_boxplot(
    aes_string(x = "Group", y = "gdhA_per_amoA", fill = "Group")
  ) +
  facet_grid(formula("Cluster + Genus + Genome ~ .")) +
  scale_fill_manual(values = sample_meta_col)
```

```{r fig.height=10, fig.width=8}
load__gene_ko_tpm() %>%
  filter(get("KO") %in% c("K00261", "K03183", "K03432", "K10944")) %>%
  mutate(Genome = gsub(".fa$", "", get("Genome"))) %>%
  left_join(
    genome_rltabd[c("Genome", "Cluster", "Taxonomy", "Layer", "Group")] %>%
      unique()
  ) %>%
  filter(taxon.split(get("Taxonomy"), 3) == "Nitrososphaeria") %>%
  group_by(
    Cluster = get("Cluster"),
    Genus = as.character(taxon.split(get("Taxonomy"), 6)),
    Genome = get("Genome"),
    Sample = paste0(get("Group"), "_", get("Layer")),
    Group = get("Group")
  ) %>%
  summarise(
    k141_1895267_per_amoA = c(
      c(get("GPM")[which(get("KO") == "K00261")], 0)[1] /
        c(get("GPM")[which(get("KO") == "K10944")], -1)[1],
      c(get("GPM")[which(get("KO") == "K03183")], 0)[1] /
        c(get("GPM")[which(get("KO") == "K10944")], -1)[1],
      c(get("GPM")[which(get("KO") == "K03432")], 0)[1] /
        c(get("GPM")[which(get("KO") == "K10944")], -1)[1]
    ),
    k141_1895267_genes = c("K00261", "K03183", "K03432")
  ) %>%
  ungroup() %>%
  filter(get("k141_1895267_per_amoA") > 0) %>%
  print() %>%
  ggplot() +
  geom_boxplot(
    aes_string(x = "Group", y = "k141_1895267_per_amoA", fill = "Group")
  ) +
  facet_grid(formula("Cluster + Genus + Genome ~ k141_1895267_genes")) +
  scale_fill_manual(values = sample_meta_col)
```

```{r sorted relative abundance of MAGs in each group}
genome_rltabd %>%
  group_by(
    Taxonomy = get("Taxonomy"), Genome = get("Genome"),
    Group = get("Group")
  ) %>%
  summarise(Relative_abundance = median(get("Relative_abundance"))) %>%
  pivot_wider(
    id_cols = c("Taxonomy", "Genome"),
    names_from = "Group",
    values_from = "Relative_abundance", values_fill = 0
  ) %>%
  .[order(apply(apply(-.[c(-1, -2)], 2, rank), 1, sum)), ] %>%
  print() %>%
  cbind(
    apply(-.[c(-1, -2)], 2, rank) %>%
      `colnames<-`(paste(colnames(.), "rank"))
  )
```

```{r extract gene gain and loss in 82_2 of Bs, fig.width=5, fig.height=45}
c82_2 <- load__genomeko() %>%
  .[, with(genome_taxonomy, get("Genome")[get("Cluster") == "82_2"])]
c82_2 %>%
  .[
    apply(. > 0, 1, . %>% unique() %>% length()) != 1,
  ] %>%
  `>`(0) %>%
  `+`(0) %>%
  pheatmap::pheatmap()
c82_2_bs_gl <- c82_2 %>%
  `>`(0) %>%
  .[
    apply(., 1, . %>% unique() %>% length()) != 1,
  ] %>%
  .[, colnames(.) != "T3L8-metabat2_75_90.1"] %>%
  .[
    apply(., 1, . %>% unique() %>% length()) == 1,
  ] %>%
  apply(1, unique) %>%
  split(names(.), .) %>%
  with(list(gain = .$`FALSE`, loss = .$`TRUE`)) %>%
  print()
```

```{r, fig.width=10, fig.height=40}
read.csv(
  file_path$file_path$results("gene_map.csv") %>%
    as.character()
) %>%
  `colnames<-`(str_to_title(colnames(.))) %>%
  filter(
    get("Genome") %in%
      with(stdb, get("Genome")[get("Secondary_cluster") == "82_2"])
  ) %>%
  .[c("Genome", "Gene")] %>%
  inner_join(
    read.csv(
      file_path$file_path$results("all_gene_annots.csv") %>%
        as.character()
    ) %>%
      `colnames<-`(c("Gene", "KO")) %>%
      .[c("KO", "Gene")]
  ) %>%
  #'  a %>%
  mutate(
    Contig = paste0(
      get("Genome"), "|", gsub("^.+\\|(.+)_\\d+$", "\\1", get("Gene"))
    ),
    ContigNGene = as.integer(gsub("^.+_(\\d+)$", "\\1", get("Gene")))
  ) %>%
  {
    contigs <- filter(., get("KO") %in% c82_2_bs_gl$loss) %>%
      group_by(Contig = get("Contig")) %>%
      filter((length(unique(get("Gene"))) > 1)) %>%
      with(get("Contig")) %>%
      unique()
    kos <- filter(., get("Contig") %in% contigs) %>%
      group_by(KO = get("KO")) %>%
      filter(length(unique(get("Gene"))) > 1) %>%
      with(get("KO")) %>%
      unique()
    filter(., get("KO") %in% c(kos)) %>%
      filter(
        (get("Contig") %in% contigs) |
          (get("Genome") == "T3L8-metabat2_75_90.1.fa")
      ) %>%
      group_by(Contig = get("Contig")) %>%
      filter((length(unique(get("Gene"))) > 1)) %>%
      ungroup()
  } %>%
  group_by(Contig = get("Contig")) %>%
  mutate(NContigGene = length(unique(get("KO")))) %>%
  ungroup() %>%
  arrange(get("Genome"), get("NContigGene"), get("ContigNGene")) %>%
  pivot_wider(
    id_cols = c("KO"), names_from = "Contig",
    values_from = "ContigNGene", values_fn = . %>% paste(collapse = ",")
  ) %>%
  column_to_rownames("KO") %>%
  apply(
    2, . %>% ifelse(is.na(.), "", .)
  ) %>%
  pheatmap::pheatmap(
    mat = (. != "") + 0,
    display_numbers = .,
    cluster_cols = FALSE,
    gaps_col = colnames(.) %>%
      gsub("\\|.+", "", .) %>%
      split(., .) %>%
      sapply(length) %>%
      reduce(function(x, y) c(x, max(x) + y))
  )
```

```{r, fig.width=15, fig.height=15}
load__gene_ko_tpm() %>%
  filter(
    get("KO") %in% c(c82_2_bs_gl$loss, "K10944", "K10945", "K10946")
  ) %>%
  mutate(Genome = gsub(".fa$", "", get("Genome"))) %>%
  left_join(
    genome_rltabd[c("Genome", "Cluster", "Taxonomy", "Layer", "Group")] %>%
      unique()
  ) %>%
  filter(taxon.split(get("Taxonomy"), 3) == "Nitrososphaeria") %>%
  mutate(Genus = as.character(taxon.split(get("Taxonomy"), 6))) %>%
  ggplot() +
  geom_boxplot(
    aes_string(x = "Group", y = "GPM", fill = "Group")
  ) +
  facet_grid(formula("Cluster + Genus + Genome ~ KO")) +
  scale_y_log10(
    labels = ~ format(.x, scientific = TRUE) %>%
      str_replace("^0e\\+0", "0e+0") %>%
      str_replace("e\\+0", "%*%10^") %>%
      parse(text = .)
  ) +
  scale_fill_manual(values = sample_meta_col)
```


```{r, fig.width=15, fig.height=15}
load__gene_ko_tpm() %>%
  inner_join(filter(key_genes, get("Pathway") == "As")) %>%
  mutate(Genome = gsub(".fa$", "", get("Genome"))) %>%
  left_join(
    genome_rltabd[c("Genome", "Cluster", "Taxonomy", "Layer", "Group")] %>%
      unique()
  ) %>%
  filter(taxon.split(get("Taxonomy"), 3) == "Nitrososphaeria") %>%
  mutate(Genus = as.character(taxon.split(get("Taxonomy"), 6))) %>%
  ggplot() +
  geom_boxplot(
    aes_string(x = "Group", y = "GPM", fill = "Group")
  ) +
  facet_grid(formula("Cluster + Genus + Genome ~ KO + Label")) +
  scale_y_log10(
    labels = ~ format(.x, scientific = TRUE) %>%
      str_replace("^0e\\+0", "0e+0") %>%
      str_replace("e\\+0", "%*%10^") %>%
      parse(text = .)
  ) +
  scale_fill_manual(values = sample_meta_col)
```
