
---
Date: 2024-02-19 14:11:51
LastEditors: Hwrn hwrn.aou@sjtu.edu.cn
LastEditTime: 2024-02-22 21:20:58
FilePath: /2021_09-MT10kSW/results/Rmd/check_niche_tree.Rmd
output:
  html_document:
    df_print: paged
    theme: cerulean
    highlight: haddock
    toc: yes
    toc_depth: 3
    toc_float:
      collapsed: no
      smooth_scroll: yes
    code_fold: hide
title: MAG co-occurence pattern using randomForest
---

```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = "~/Work/2021_09-MT10kSW/")
```

```{r config, message=FALSE, warning=FALSE}
source("workflow/utils/RLib.local/R/init.r", chdir = TRUE)
```

```{r load_data, cache=TRUE, dependson=c("config")}
taxon_color <- load__taxon_color()

stdb <- load__Stdb()
wtdb <- load__Wtdb()
genome_taxonomy <- load__genome_taxonomy(stdb, wtdb)

genome_rltabd <-
  stringr::str_glue("Wtdb.relative_abundance.tsv") %>%
  file_path$file_path$results(.) %>%
  as.character() %>%
  get_relative_abundance(genome_taxonomy) %>%
  mutate(
    Taxa_label = sapply(taxon.split(get("Taxonomy"), 1, 7), get_taxon_color)
  )

genomeko <- load__genomeko()
gmodule <- file_path$file_path$results("gmodule.csv") %>%
  as.character %>%
  load_gmodule(symnum = FALSE) %>%
  `colnames<-`(colnames(.) %>% gsub(".fa", "", .))
#' gene_ko_tpm <- load__gene_ko_tpm()

key_genes <- load__key_genes()
pathway_col <- set__pathway_col(key_genes$Pathway)
```

## test randomforest
```{.r rf of each class}
class_rf <- otu_group %>%
  split(
    .,
    column_to_rownames(genome_taxonomy, "Genome")[rownames(.), "Taxonomy"] %>%
      taxon.split(1, 3)
  ) %>%
  lapply(
    . %>%
      {
        if (length(unique(.$groups)) == 1) {
          print(
            paste(
              column_to_rownames(genome_taxonomy, "Genome")[
                rownames(.)[1], "Taxonomy"
              ] %>%
                taxon.split(1, 3),
              "均能在 Bw 中存在, 跳过"
            )
          )
          return(NULL)
        } else {
          print(
            paste(
              column_to_rownames(genome_taxonomy, "Genome")[
                rownames(.)[1], "Taxonomy"
              ] %>%
                taxon.split(1, 3),
              "..."
            )
          )
        }
        set.seed(1)

        otu_train <- .
        otu_train_forest <- randomForest::randomForest(
          formula("groups ~ ."),
          data = otu_train, importance = TRUE
        )
        otu_train_forest %>%
          {
            print(.)
            # 可以解释时间变化的75.02%
            if (.$type == "regression") {
              print(paste("可以解释时间变化的", .$rsq %>% .[length(.)]))

              plot(.$predicted, otu_train$groups, main = "", col = "blue")
              abline(1, 1)
            } else if (.$type == "classification") {
              #' print(table(otu_train$groups, .$predicted))
              #' 行和是实际值, 列和是预测值
              print(
                paste(
                  column_to_rownames(genome_taxonomy, "Genome")[
                    rownames(otu_train)[1], "Taxonomy"
                  ] %>%
                    taxon.split(1, 3),
                  "预测的准确率:",
                  1 - .$err.rate[.$ntree, "OOB"]
                )
              )
            }
          }
        otu_train_forest
      }
  )
```

```{r do estimation}
genome_group_otu <- genome_rltabd %>%
  {
    abd <- .
    otus <- unique(abd$Genome)
    otu_annot <- get_taxon_group(abd, "Genome")
    otu_raw <- cbind(
      t(genomeko[, otus]),
      t(gmodule[, otus]),
      stdb %>%
        mutate(
          Genome = gsub(".fa$", "", get("Genome")),
          Cluster = get("Secondary_cluster")
        ) %>%
        right_join(
          filter(mutate(genome_taxonomy, Genome = NULL), get("Rep"))
        ) %>%
        mutate(
          Source = get("Group"),
          Domain = taxon.split(get("Taxonomy"), 1, 1),
          Phylum = taxon.split(get("Taxonomy"), 1, 2),
          Class = taxon.split(get("Taxonomy"), 1, 3),
          Order = taxon.split(get("Taxonomy"), 1, 4),
          Family = taxon.split(get("Taxonomy"), 1, 5),
          Genus = taxon.split(get("Taxonomy"), 1, 6),
          Species = taxon.split(get("Taxonomy"), 1, 7),
        ) %>%
        dplyr::select(
          "Genome",
          "Score", "Completeness", "Contamination", "Strain.heterogeneity",
          "Genomesize", "Gc", # "Source",
          "Domain", "Phylum", "Class" # , "Order", "Family", "Genus", "Species"
        ) %>%
        filter(get("Genome") %in% otus) %>%
        column_to_rownames("Genome") %>%
        .[otus, ]
    )

    l <- abd$Group %>%
      unique() %>%
      `names<-`(., .) %>%
      lapply(
        . %>%
          {
            groups <- filter(otu_annot, get(.) != "")$Genome
            otu_raw %>%
              data.frame(groups = as.factor(rownames(.) %in% groups), .)
          }
      )
  }

genome_group_nfs <- site_group$Group %>%
  unique() %>%
  `names<-`(., .) %>%
  lapply(
    . %>%
      {
        otu_group <- genome_group_otu[[.]]
        set.seed(1)

        select_train <- dim(otu_group)[1] %>% sample(. * 0.8)
        otu_train <- otu_group
      } %>%
      randomForest::randomForest(
        formula("groups ~ ."),
        data = ., importance = TRUE
      )
  )

site_group$Group %>%
  unique() %>%
  sapply(
    . %>%
      {
        print(.)
        otu_group <- genome_group_otu[[.]]

        genome_group_nfs[[.]] %>%
          {
            select_train <- rownames(otu_group) %in% names(.$predicted)
            otu_train <- otu_group[select_train, ]
            otu_test <- otu_group[!select_train, ]
            # 可以解释时间变化的75.02%
            if (.$type == "regression") {
              print(paste("可以解释时间变化的", .$rsq %>% .[length(.)]))

              plot(.$predicted, otu_train$groups, main = "")
              points(predict(., otu_test), otu_test$groups, col = "red")
              abline(1, 1)
            } else if (.$type == "classification") {
              #' print(table(otu_train$groups, .$predicted))
              #' 行和是实际值, 列和是预测值
              print(table(otu_train$groups, .$predicted))
              print(
                paste("预测的准确率:", 1 - .$err.rate[.$ntree, "OOB"])
              )
              if (length(otu_test$groups) > 0) {
                print(table(otu_test$groups, predict(., otu_test)))
                print(
                  paste(
                    "验证的准确率:",
                    (function(x) sum(x) / length(x))(
                      otu_test$groups == predict(., otu_test)
                    )
                  )
                )
              } else {
                1 - .$err.rate[.$ntree, "OOB"]
              }
            }
          }
      }
  )
```

```{r, fig.width=10, fig.height=7}
genome_rltabd %>%
  group_by(Genome = get("Genome"), Group = get("Group")) %>%
  summarise(
    Mean = mean(get("Relative_abundance")),
    TaxLabel = get_taxon_color(taxon.split(unique(get("Taxonomy")), 1, 7))
  ) %>%
  ungroup() %>%
  group_by(Group = get("Group")) %>%
  mutate(
    Predicted = ifelse(
      as.logical(
        genome_group_nfs[[unique(get("Group"))]]$predicted[get("Genome")]
      ),
      "predict exist", "predict not exist"
    ) %>%
      factor(levels = c("predict not exist", "predict exist"), ordered = TRUE),
    Vote = genome_group_nfs[[unique(get("Group"))]]$votes[get("Genome"), 2],
    OBBerr = genome_group_nfs[[unique(get("Group"))]] %>%
      {
        .$err.rate[.$ntree, "OOB"]
      },
    GroupLabel = paste0(get("Group"), " (Accurate = ", 1 - get("OBBerr"), ")")
  ) %>%
  {
    list(
      ggplot(., mapping = aes_string(x = "Vote", y = "Mean")) +
        geom_density_2d() +
        geom_point(aes_string(color = "TaxLabel")),
      ggplot(., mapping = aes_string(x = "Predicted", y = "Mean")) +
        geom_boxplot(aes_string(color = "TaxLabel")) +
        geom_violin(fill = NA) +
        # geom_jitter() +
        ggsignif::geom_signif(
          #' comparisons = . %>% .$Predicted %>% unique %>% list(.)
          comparisons = list(c("predict exist", "predict not exist")),
          tip_length = 0, margin_top = 0.01
        )
    )
  } %>%
  lapply(
    . %>%
      `+`(guides(color = guide_legend(ncol = 1, reverse = TRUE))) %>%
      `+`(
        scale_color_manual(
          values = c(taxon_color$LEGEND_COLORS) %>%
            `names<-`(taxon_color$LEGEND_LABELS) %>%
            .[order(names(.))]
        )
      ) %>%
      `+`(facet_wrap(formula("GroupLabel ~ ."), nrow = 2)) %>%
      `+`(labs(x = "", y = "Mean abundance")) %>%
      `+`(scale_y_log10()) %>%
      `+`(theme_minimal())
  )
```

```{r, fig.width=10, fig.height=7}
genome_rltabd %>%
  {
    a <- get_taxon_group(., "Genome") %>%
      column_to_rownames("Genome") %>%
      `!=`("")
    b <- genome_group_nfs %>%
      lapply(
        . %>%
          .$predicted %>%
          data.frame(Var = .) %>%
          rownames_to_column("Genome")
      ) %>%
      bind_rows(.id = "Group") %>%
      pivot_wider(
        id_cols = "Genome", names_from = "Group", values_from = "Var"
      ) %>%
      column_to_rownames("Genome") %>%
      .[rownames(a), colnames(a)]
    mutate(., Taxon = as.character(taxon.split(get("Taxonomy"), 1, 6))) %>%
      with(split(., get("Taxon"))) %>%
      lapply(. %>% with(data.frame(a == b)[unique(get("Genome")), ]))
  } %>%
  sapply(
    . %>%
      {
        sl <- function(x) sum(x) / length(x)
        data.frame(
          NGenome = dim(.)[1],
          AllAcc = sl(c(as.matrix(.))), t(apply(., 2, sl))
        )
      }
  ) %>%
  t() %>%
  apply(2, unlist) %>%
  as.data.frame() %>%
  rownames_to_column("Taxon") %>%
  filter(get("NGenome") > 1) %>%
  dplyr::arrange(-get("NGenome"), -get("AllAcc"), get("Taxon"))
  
genome_rltabd %>%
  {
    a <- get_taxon_group(., "Genome") %>%
      column_to_rownames("Genome") %>%
      `!=`("")
    b <- genome_group_nfs %>%
      lapply(
        . %>%
          .$predicted %>%
          data.frame(Var = .) %>%
          rownames_to_column("Genome")
      ) %>%
      bind_rows(.id = "Group") %>%
      pivot_wider(
        id_cols = "Genome", names_from = "Group", values_from = "Var"
      ) %>%
      column_to_rownames("Genome") %>%
      .[rownames(a), colnames(a)]
    ab <- mutate(., Taxon = as.character(taxon.split(get("Taxonomy"), 1, 4))) %>%
      with(split(., get("Taxon"))) %>%
      lapply(
        . %>% with(list(a[unique(get("Genome")), ], b[unique(get("Genome")), ]))
      )
    sl <- function(x) sum(x) / length(x)
    for (i in names(ab)) {
      if (sl(c(ab[[i]][[1]] == ab[[i]][[2]])) == 1) {
        if (dim(ab[[i]][[2]])[1] > 1) {
          print(i)
          print(ab[[i]][[1]])
        }
      } else if (sl(c(ab[[i]][[1]] == ab[[i]][[2]])) > 0.9) {
        print(i)
        print(ab[[i]][[1]])
        print(ab[[i]][[2]] == ab[[i]][[1]])
      }
    }
  }
  c(
    "Bacteria;Planctomycetota;Planctomycetes;Pirellulales",
    "Bacteria;Proteobacteria;Gammaproteobacteria;Xanthomonadales"
  )
```

```{r}
site_group$Group %>%
  unique() %>%
  `names<-`(., .) %>%
  lapply(
    . %>%
      {
        otu_group <- genome_group_otu[[.]]
        set.seed(1)

        select_train <- dim(otu_group)[1] %>% sample(. * 0.8)
        otu_train <- otu_group %>%
          .[.$Class == "Archaea;Thermoproteota;Nitrososphaeria", ]
      } %>%
      randomForest::randomForest(
        formula("groups ~ ."),
        data = ., ntree = 1000
      )
  )
```

```{r n important factors, fig.width=14, fig.height=10}
# OTUs
par(mfrow = c(1, 4)) %>%
  {
    site_group$Group %>%
      unique() %>%
      lapply(
        . %>%
          {
            print(.)

            n_var <- 80
            imp <- randomForest::importance(genome_group_nfs[[.]])
            ord <- rev(
              order(imp[, "MeanDecreaseAccuracy"], decreasing = TRUE)[1:n_var]
            )
            xmin <- min(imp[ord, "MeanDecreaseAccuracy"])
            dotchart(
              imp[ord, "MeanDecreaseAccuracy"],
              xlab = colnames(imp)["MeanDecreaseAccuracy"],
              ylab = "",
              main = .,
              xlim = c(xmin, max(imp[, "MeanDecreaseAccuracy"]))
            )
          }
      )
    par(.)
  }

# Mean Decrease Accuracy
site_group$Group %>%
  unique() %>%
  `names<-`(., .) %>%
  lapply(
    . %>%
      {
        n_var <- 80
        imp <- randomForest::importance(genome_group_nfs[[.]])
        ord <- rev(
          order(imp[, "MeanDecreaseAccuracy"], decreasing = TRUE)[1:n_var]
        )
        data.frame(MeanDecreaseAccuracy = imp[ord, "MeanDecreaseAccuracy"]) %>%
          rownames_to_column("KO")
      }
  ) %>%
  bind_rows(.id = "Group") %>%
  inner_join(key_genes)

# Rank Decrease Accuracy
rank_var_accuracy <- site_group$Group %>%
  unique() %>%
  `names<-`(., .) %>%
  lapply(
    . %>%
      {
        imp <- randomForest::importance(genome_group_nfs[[.]])
        ord <- rev(
          order(imp[, "MeanDecreaseAccuracy"], decreasing = TRUE)
        )
        data.frame(MeanDecreaseAccuracy = imp[ord, "MeanDecreaseAccuracy"]) %>%
          rownames_to_column("Var")
      }
  ) %>%
  bind_rows(.id = "Group") %>%
  pivot_wider(
    id_cols = "Var", names_from = "Group",
    values_from = "MeanDecreaseAccuracy"
  ) %>%
  column_to_rownames("Var") %>%
  .[order(-apply(apply(., 2, rank), 1, mean)), ] %>%
  rownames_to_column("Var")

rank_var_accuracy %>%
  left_join(
    read.csv("data/kegglist_v1.tsv", sep = "\t", header = FALSE) %>%
      `colnames<-`(c("Var", "Desc"))
  ) %>%
  dplyr::select("Desc", "Var", dplyr::everything())
```

```{r check select vars, fig.width=10, fig.height=7}
vars_100 <- head(rank_var_accuracy$Var, 100)
site_group$Group %>%
  unique() %>%
  `names<-`(., .) %>%
  lapply(
    . %>%
      {
        otu_group <- genome_group_otu[[.]][c("groups", vars_100)]
        set.seed(1)

        select_train <- dim(otu_group)[1] %>% sample(. * 0.8)
        otu_train <- otu_group
      } %>%
      randomForest::randomForest(
        formula("groups ~ ."),
        data = ., importance = TRUE
      )
  )

ggroup_vars_100 <- genome_group_otu %>%
  lapply(
    . %>%
      .[c("groups", vars_100)] %>%
      rownames_to_column("Genom") %>%
      dplyr::arrange(get("Class")) %>%
      dplyr::select(!c("Phylum")) %>%
      group_by(Class = get("Class")) %>%
      filter(length(unique(get("groups"))) > 1) %>%
      with(split(., as.character(get("Class")))) %>%
      lapply(
        . %>% .[!apply(., 2, . %>% unique() %>% length() %>% `==`(1))]
      )
  )
ggroup_vars_100 %>%
  lapply(
    . %>%
      sapply(. %>% dim() %>% `names<-`(c("NGenome", "NVar"))) %>%
      t() %>%
      as.data.frame() %>%
      rownames_to_column("Class")
  ) %>%
  bind_rows() %>%
  unique() %>%
  dplyr::arrange(get("Class"))
ggroup_vars_100 %>%
  lapply(
    . %>%
      .[["Archaea;Thermoproteota;Nitrososphaeria"]] %>%
      dplyr::arrange(get("groups"), -get("Score"))
  )
```

```{.r otu_train_cv}
set.seed(1)
otu_train_cv_raw <- replicate(
  5,
  randomForest::rfcv(
    otu_group[-ncol(otu_group)], otu_group$group,
    cv.fold = 10, step = 1.5
  ),
  simplify = FALSE
)

otu_train_cv <- data.frame(sapply(otu_train_cv_raw, "[[", "error.cv")) %>%
  mutate(otus = as.numeric(rownames(.))) %>%
  pivot_longer(!"otus", names_to = "variable", values_to = "value")

p <- ggplot(otu_train_cv, aes_string(x = "otus", y = "value")) +
  geom_smooth(se = FALSE, method = "glm", formula = y ~ splines::ns(x, 6)) +
  theme(
    panel.grid = element_blank(),
    panel.background = element_rect(color = "black", fill = "transparent")
  ) +
  labs(title = "", x = "Number of OTUs", y = "Cross-validation error") +
  geom_vline(xintercept = 50)
p
```
